PenguinCatcher/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace PlantShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PenguinCatcher/Areas/User/Controllers/CreationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PenguinCatcher.Areas.User.Models.ViewModels;
using PenguinCatcher.DataAccess;
using PenguinCatcher.Models.DomainModels;
using PenguinCatcher.Models.IdentityModels;
using System.Security.Claims;

namespace PenguinCatcher.Areas.User.Controllers
{
    [Area("User")]
    public class CreationController : Controller
    {
        private readonly PenguinContext _context;
        private readonly UserManager<PenguinCatcherUser> _userManager;

        public CreationController(PenguinContext context, UserManager<PenguinCatcherUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        [HttpGet]
        public IActionResult CreateDistro()
        {
            return View(new DistroViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDistro(DistroViewModel distribution)
        {
            if (ModelState.IsValid)
            {
                Distribution newDistro = new Distribution { DistroName = distribution.DistroName, Developer = distribution.Developer, DistroURL = distribution.DistroUrl, ReleaseCycle = distribution.ReleaseCycle };
                
                if (_context.Distributions.Where(d => d.DistroName == newDistro.DistroName).ToList().Count == 0)
                    _context.Add(newDistro);
                
                await _context.SaveChangesAsync();

                return Redirect("/User/Dashboard/Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult CreatePost()
        {
            ViewBag.AvailableDistros = _context.Distributions.ToList();

            return View(new PostViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(PostViewModel post)
        {
            if (ModelState.IsValid)
            {
                Post newPost = new Post();

                newPost.Content = post.Content;

                newPost.Distribution = _context.Distributions.Where(d => d.DistroName == post.DistroName).First();

                var currUser = (await _userManager.GetUserAsync(HttpContext.User))!;
                newPost.User = currUser;

                newPost.DatePosted = DateTime.Now;

                _context.Add(newPost);
                await _context.SaveChangesAsync();

                if (await _userManager.IsInRoleAsync(currUser, "Admin"))
                    return Redirect("/Admin/Dashboard/Index");
                else if (await _userManager.IsInRoleAsync(currUser, "Catcher"))
                    return Redirect("/User/Dashboard/Index");
            }

            return View();
        }
    }
}

PenguinCatcher/Areas/User/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PenguinCatcher.DataAccess;
using PenguinCatcher.Models.IdentityModels;
using System.Security.Claims;

namespace PenguinCatcher.Areas.NormalUser.Controllers
{
    [Authorize(Roles = "Catcher")]
    [Area("User")]
    public class DashboardController : Controller
    {
        private readonly PenguinContext _context;
        private readonly UserManager<PenguinCatcherUser> _userManager;

        public DashboardController(PenguinContext context, UserManager<PenguinCatcherUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_context.Posts.Where(p => p.User.Id == User.FindFirstValue(ClaimTypes.NameIdentifier)).OrderByDescending(p => p.DatePosted).Reverse().Take(3).ToList());
        }
    }
}

PenguinCatcher/Areas/User/Controllers/PostController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PenguinCatcher.DataAccess;
using PenguinCatcher.Models;
using PenguinCatcher.Models.DomainModels;
using PenguinCatcher.Models.IdentityModels;

namespace PenguinCatcher.Areas.User.Controllers
{
    [Area("User")]
    public class PostController : Controller
    {
        private readonly PenguinContext _context;
        private readonly UserManager<PenguinCatcherUser> _userManager;

        public PostController(PenguinContext context, UserManager<PenguinCatcherUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> UserPosts(int? pageNum)
        {
            var currUser = await _userManager.GetUserAsync(HttpContext.User);

            ViewBag.Pages = await PaginatedPage<Post>.CreateAsync(_context.Posts.Where(p => p.User == currUser).Include(p => p.Distribution), pageNum ?? 1, 5);

            return View("PostsPage");
        }
    }
}

PenguinCatcher/Areas/User/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "User Dashboard";
}

@model List<PenguinCatcher.Models.DomainModels.Post>

<h1>Welcome back, @User.Identity.Name!</h1>

<div class="container row">
    <div class="d-flex flex-column align-items-center col me-3 border  p-2">
        <h2>Your Recently Created Posts</h2>

        @if (Model.Count > 0)
        {
            foreach (var post in Model.Take(3))
            {
                <div class="container border mb-3">
                    <p>@post.Content</p>
                    <p>Date posted: @post.DatePosted</p>
                </div>
            }

            <a class="btn btn-primary" asp-area="User" asp-action="UserPosts" asp-controller="Post">View the rest here!</a>
        }
        else
        {
            <p>You do not have any posts yet</p>
        }
    </div>

    <div class="d-flex flex-column col border p-2 justify-content-center align-items-center">
        <h2 class="">Make something new!</h2>
        <div class="">
            <a class="btn btn-primary col flex-grow-0" class="btn btn-primary" asp-area="User" asp-controller="Creation" asp-action="CreateDistro">Create a new Distro</a>
            <a class="btn btn-primary col flex-grow-0" class="btn btn-primary" asp-area="User" asp-controller="Creation" asp-action="CreatePost">Create a new Post</a>
        </div>
    </div>
</div>