PenguinCatcher/Areas/User/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PenguinCatcher.DataAccess;
using PenguinCatcher.Models.IdentityModels;
using System.Security.Claims;

namespace PenguinCatcher.Areas.NormalUser.Controllers
{
    [Authorize(Roles = "Catcher")]
    [Area("User")]
    public class DashboardController : Controller
    {
        private readonly PenguinContext _context;
        private readonly UserManager<PenguinCatcherUser> _userManager;

        public DashboardController(PenguinContext context, UserManager<PenguinCatcherUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_context.Posts.Where(p => p.User.Id == User.FindFirstValue(ClaimTypes.NameIdentifier)).OrderByDescending(p => p.DatePosted).Reverse().Take(3).ToList());
        }
    }
}

PenguinCatcher/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PenguinCatcher.DataAccess;
using PenguinCatcher.Models.ViewModels;
using PenguinCatcher.Models.DomainModels;
using Microsoft.AspNetCore.Identity;
using PenguinCatcher.Models.IdentityModels;
using System.Security.Claims;
using PenguinCatcher.Models;

namespace PenguinCatcher.Controllers
{
    public class PostsController : Controller
    {
        private readonly PenguinContext _context;
        private readonly UserManager<PenguinCatcherUser> _userManager;

        public PostsController(PenguinContext context, UserManager<PenguinCatcherUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Page(int? pageNum)
        {
            ViewBag.Pages = await PaginatedPage<Post>.CreateAsync(_context.Posts.Include(p => p.User).Include(p => p.Distribution), pageNum ?? 1, 5);
            return View("PostsPage");
        }

        public IActionResult Post(int postId)
        {
            ViewBag.CurrUserID = _userManager.GetUserId(HttpContext.User);

            return View(_context.Posts.Where(p => p.PostID == postId).Include(p => p.Distribution).Include(p => p.User).Include(p => p.Likes).Include(p => p.Comments).ThenInclude(c => c.User).First());
        }

        [HttpGet]
        public async Task<IActionResult> Like(int postId, string goodBad)
        {
            if (goodBad.Equals("like"))
            {
                var post = _context.Posts.Where(p => p.PostID == postId).First();

                Like newLike = new Like();
                newLike.Post = post;

                newLike.User = (await _userManager.GetUserAsync(HttpContext.User))!;

                newLike.Post = post;

                post.Likes.Add(newLike);
            }
            else if (goodBad.Equals("dislike"))
            {
                var post = _context.Posts.Where(p => p.PostID == postId).Include(p => p.Likes).First();

                var like = post.Likes.Where(l => l.UserId == _userManager.GetUserId(HttpContext.User)).First();

                post.Likes.Remove(like);
            }
            

            _context.SaveChanges();

            return Redirect($"/Posts/Post?postId={postId}");
        }

        [HttpGet]
        public IActionResult Comment(int postId)
        {
            return View(new CommentViewModel { PostId = postId });
        }

        [HttpPost]
        public async Task<IActionResult> Comment(CommentViewModel cvm)
        {
            var newComment = new Comment();

            Console.WriteLine(cvm.PostId);

            newComment.Post = _context.Posts.Where(p => p.PostID == cvm.PostId).First();

            newComment.User = (await _userManager.GetUserAsync(HttpContext.User))!;

            newComment.Content = cvm.Content;

            _context.Comments.Add(newComment);

            _context.SaveChanges();

            return Redirect($"/Posts/Post?postId={cvm.PostId}");
        }
    }
}

PenguinCatcher/Views/Shared/PostsPage.cshtml
@{
    Layout = "_PaginatedPagePresentation";
}

@if (ViewBag.Pages != null)
{
    @foreach (Post post in ViewBag.Pages)
    {
        <div class="container row align-items-center justify-content-center border m-1 p-2">
            <p class="col text-center">@post.Distribution.DistroName</p> <p class="col text-center">@(post.Content.Length < 20 ? @post.Content : @post.Content.Substring(0, 20) + "...")</p> <p class="col text-center">Post by: @post.User.UserName</p> <a class="btn btn-primary col-2 text-center" asp-area="" asp-controller="Posts" asp-action="Post" asp-route-postId="@post.PostID">View whole post here</a>
        </div>
    }
}

PenguinCatcher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - PenguinCatcher</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/PenguinCatcher.styles.css" asp-append-version="true" />
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PenguinCatcher</a>
                    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>

                            

                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item mx-2">
                                    <a class="btn btn-primary" asp-controller="Account" asp-action="Login">Login</a>
                                </li>

                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item mx-2">
                                    <a class="nav-link text-dark" asp-area="@(User.IsInRole("Admin") ? "Admin" : "User")" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                </li>

                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="LogOut">Log out</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2024 - PenguinCatcher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

PenguinCatcher/Views/Shared/_PaginatedPagePresentation.cshtml
@{
    Layout = "_Layout";
}

@model PenguinCatcher.Models.PaginatedPage<Post>

@if (ViewBag.Pages != null)
{
    @RenderBody();

    @if (!(ViewBag.Pages.HasNextPage == false && ViewBag.Pages.HasPrevious == false))
    {
        <div class="container row align-items-center justify-content-center">
            <a class="btn btn-primary flex-grow-0 col-1 @(ViewBag.Pages.HasPrevious ? "" : "disabled")" asp-area="" asp-controller="Posts" asp-action="Page" asp-route-pageNum="@(ViewBag.Pages.PageIndex - 1)">Prev</a>
            <p class="col-1 mb-0 mx-2 py-1 border">@ViewBag.Pages.PageIndex / @ViewBag.Pages.TotalPages</p>
            <a class="btn btn-primary flex-grow-0 col-1 @(ViewBag.Pages.HasNextPage ? "" : "disabled")" asp-area="" asp-controller="Posts" asp-action="Page" asp-route-pageNum="@(ViewBag.Pages.PageIndex + 1)">Next</a>
        </div>
    }
}