PenguinCatcher/Areas/User/Controllers/CreationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PenguinCatcher.Areas.User.Models.ViewModels;
using PenguinCatcher.DataAccess;
using PenguinCatcher.Models.DomainModels;
using PenguinCatcher.Models.IdentityModels;
using System.Security.Claims;

namespace PenguinCatcher.Areas.User.Controllers
{
    [Area("User")]
    public class CreationController : Controller
    {
        private readonly PenguinContext _context;
        private readonly UserManager<PenguinCatcherUser> _userManager;

        public CreationController(PenguinContext context, UserManager<PenguinCatcherUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        [HttpGet]
        public IActionResult CreateDistro()
        {
            return View(new DistroViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDistro(DistroViewModel distribution)
        {
            if (ModelState.IsValid)
            {
                Distribution newDistro = new Distribution { DistroName = distribution.DistroName, Developer = distribution.Developer, DistroURL = distribution.DistroUrl, ReleaseCycle = distribution.ReleaseCycle };
                
                if (_context.Distributions.Where(d => d.DistroName == newDistro.DistroName).ToList().Count == 0)
                    _context.Add(newDistro);
                
                await _context.SaveChangesAsync();

                return Redirect("/User/Dashboard/Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult CreatePost()
        {
            ViewBag.AvailableDistros = _context.Distributions.ToList();

            return View(new PostViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(PostViewModel post)
        {
            if (ModelState.IsValid)
            {
                Post newPost = new Post();

                newPost.Content = post.Content;

                newPost.Distribution = _context.Distributions.Where(d => d.DistroName == post.DistroName).First();

                var currUser = (await _userManager.GetUserAsync(HttpContext.User))!;
                newPost.User = currUser;

                newPost.DatePosted = DateTime.Now;

                _context.Add(newPost);
                await _context.SaveChangesAsync();

                if (await _userManager.IsInRoleAsync(currUser, "Admin"))
                    return Redirect("/Admin/Dashboard/Index");
                else if (await _userManager.IsInRoleAsync(currUser, "Catcher"))
                    return Redirect("/User/Dashboard/Index");
            }

            return View();
        }
    }
}

PenguinCatcher/Areas/User/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PenguinCatcher.DataAccess;
using PenguinCatcher.Models.IdentityModels;
using System.Security.Claims;

namespace PenguinCatcher.Areas.NormalUser.Controllers
{
    [Authorize(Roles = "Catcher")]
    [Area("User")]
    public class DashboardController : Controller
    {
        private readonly PenguinContext _context;
        private readonly UserManager<PenguinCatcherUser> _userManager;

        public DashboardController(PenguinContext context, UserManager<PenguinCatcherUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_context.Posts.Where(p => p.User.Id == User.FindFirstValue(ClaimTypes.NameIdentifier)).OrderByDescending(p => p.DatePosted).Reverse().Take(3).ToList());
        }
    }
}

PenguinCatcher/Areas/User/Views/Creation/CreateDistro.cshtml
@model DistroViewModel

<form method="post" asp-controller="Creation" asp-action="CreateDistro">
    <div class="row mb-2">
        <label class="col-form-label col-md-2">Enter the distribution's name: </label>
        
        <div class="col-md-4">
            <input asp-for="DistroName" class="form-control" />
        </div>
    </div>
    
    <div class="row mb-2">
        <label class="col-form-label col-md-2">Enter the distribution's release cycle: </label>

        <div class="col-md-4">
            <input asp-for="ReleaseCycle" class="form-control" />
        </div>
    </div>

    <div class="row mb-2">
        <label class="col-form-label col-md-2">Enter the distribution's developer: </label>

        <div class="col-md-4">
            <input asp-for="Developer" class="form-control" />
        </div>
    </div>

    <div class="row mb-2">
        <label class="col-form-label col-md-2">Enter the distribution's website URL: </label>

        <div class="col-md-4">
            <input asp-for="DistroUrl" class="form-control" />
        </div>
    </div>

    <input type="submit" value="Create" class="btn btn-primary" />
</form>

<a class="btn" asp-area="User" asp-controller="Dashboard" asp-action="Index">Cancel</a>

PenguinCatcher/Areas/User/Views/Creation/CreatePost.cshtml
@model PostViewModel

<form method="post" asp-controller="Creation" asp-action="CreatePost">
    <div class="row mb-2">
        <label class="col-form-label col-md-2">Enter the distribution's name: </label>

        <div class="col-md-4">
            <select class="form-select" asp-for="DistroName">
                @foreach (Distribution distro in ViewBag.AvailableDistros)
                {
                    <option value="@distro.DistroName.ToLower()">@distro.DistroName</option>
                }
            </select>
        </div>

        <label class="col-form-label col-md-2">Enter the content of the post: </label>

        <div class="col-md-4">
            <textarea class="form-control" asp-for="Content"></textarea>
        </div>
    </div>

    <input type="submit" value="Create" class="btn btn-primary" />
</form>

<a class="btn" asp-area="User" asp-controller="Dashboard" asp-action="Index">Cancel</a>